myapp/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name='myapp'
urlpatterns = [
    path('',views.index),
    path('product/',views.product,name="product"),
    #path('product/',views.Productlistview.as_view(),name="product"),
    # path('product/<int:id>',views.product_detail,name="product_detail"),
    path('product/<int:pk>',views.ProductDetailView.as_view(),name="product_detail"),
    # path('product/add',views.add_product,name="add_product"),
    path('product/add',views.ProductCreateView.as_view(),name="add_product"),
    path('product/update/<int:id>',views.update_product,name="update_product"),
    path('product/delete/<int:id>',views.delete_product,name="delete_product"),
    path('product/mylistings',views.my_listings,name="mylistings"),
] 

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('myapp/',include('myapp.urls')),
    path('users/',include('users.urls')),
]

urlpatterns+= static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)

users/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from django.contrib.auth import views as authentication_views

app_name='users'
urlpatterns = [
    path('register/',views.register,name="register"),
    path('login/', authentication_views.LoginView.as_view(template_name='users/login.html'),name="login"),
    path('logout/', authentication_views.LogoutView.as_view(template_name='users/logout.html'),name="logout"),
    path('profile', views.profile,name="profile"),
    path('createprofile', views.createprofile,name="createprofile"),
    path('sellerprofile/<int:id>/', views.seller_profile, name="sellerprofile"),
]

myapp/models.py
from audioop import reverse
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Myproduct(models.Model):
    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('myapp:product')
    
    seller_name = models.ForeignKey(User, on_delete=models.CASCADE, default=1)
    name = models.CharField(max_length=100)
    price = models.IntegerField()
    desc = models.CharField(max_length=200)
    image = models.ImageField(blank=True,upload_to='images')

users/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Profile(models.Model):
    def __str__(self):
        return self.user.username
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    image = models.ImageField(default='profile.jpg',upload_to = "profile_pictures")
    contact_number = models.CharField(max_length=100,default='9999999999')

users/forms.py
from dataclasses import field
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms

class NewUserForm(UserCreationForm):
    email = forms.EmailField(required=True, widget=forms.EmailInput(attrs={'class':'focus:outline-none', 'placeholder':'demo@gmail.com'}))
    username= forms.CharField(required=True, widget=forms.TextInput(attrs={'class':'focus:outline-none', 'placeholder':'user123'}))
    password1: forms.CharField(required=True, widget=forms.PasswordInput(attrs={'class':'focus:outline-none'}))
    password2: forms.CharField(required=True, widget=forms.PasswordInput(attrs={'class':'focus:outline-none'}))

    class Meta:
        model = User
        fields = ("username","email","password1","password2")

    def save(self, commit=True):
        user = super(NewUserForm,self).save(commit=False)
        user.email = self.cleaned_data['email']
        if commit:
            user.save()
        return user

myapp/views.py
from django.shortcuts import redirect, render
from django.http import HttpResponse
from .models import Myproduct
from django.contrib.auth.decorators import login_required
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView
from django.core.paginator import Paginator

# Create your views here.
def index(request):
    return HttpResponse('hello world')

def product(request):
    page_obj = myproduct = Myproduct.objects.all()

    product_name = request.GET.get('product_name')
    if product_name != '' and product_name is not None:
        page_obj = myproduct.filter(name__icontains=product_name)

    paginator = Paginator(page_obj,3)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {'page_obj':page_obj}
    return render(request, 'myapp/index.html', context)


#Class based view for above products view [Listview]
# class Productlistview(ListView):
#     model = Myproduct
#     template_name = 'myapp/index.html'
#     context_object_name = 'myproduct'
#     paginate_by = 3


# def product_detail(request,id):
#     product = Myproduct.objects.get(id=id)
#     context = {'product':product}
#     return render(request,'myapp/detail.html',context)

#class based view for above product detail view
class ProductDetailView(DetailView):
    model = Myproduct
    template_name = 'myapp/detail.html'
    context_object_name = 'product'

# @login_required
# def add_product(request):
#     if request.method=='POST':
#         name = request.POST.get('name')
#         price = request.POST.get('price')
#         desc = request.POST.get('desc')
#         image = request.FILES['upload']
#         seller_name = request.user
#         product = Myproduct(name=name,price=price,desc=desc,image=image,seller_name=seller_name)
#         product.save()
#     return render(request,'myapp/addproduct.html')

#class based view for creating a product
class ProductCreateView(CreateView):
    model = Myproduct
    fields = ['name','price','desc','image','seller_name']   

def update_product(request,id):
    product = Myproduct.objects.get(id=id)
    context = {'product':product}
    if request.method=='POST':
        product.name = request.POST.get('name')
        product.price = request.POST.get('price')
        product.desc = request.POST.get('desc')
        product.image = request.FILES['upload']
        product.save()
        return redirect('/myapp/product')
    return render(request,'myapp/updateproduct.html', context)

def delete_product(request,id):
    product = Myproduct.objects.get(id=id)
    context = {
        'product':product,
    }
    if request.method == 'POST':
        product.delete()
        return redirect('/myapp/product')
    return render(request,'myapp/delete.html',context)

def my_listings(request):
    product = Myproduct.objects.filter(seller_name=request.user)
    context = {
        'product':product
    }

    return render(request, 'myapp/mylisting.html',context)

users/views.py
from django.http import HttpResponse
from django.shortcuts import redirect, render

from .models import Profile
from .forms import NewUserForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User

# Create your views here.
def register(request):
    if request.method == 'POST':
        form = NewUserForm(request.POST)
        if form.is_valid():
            user = form.save()
            return redirect('./myapp/register')
        else:
            print(form.errors.as_data())
            return HttpResponse(form.errors.as_text())
    form = NewUserForm
    context = {
        'form':form,
    }
    return render(request, 'users/register.html', context)

@login_required    
def profile(request):
    return render(request,'users/profile.html')

def createprofile(request):
    if request.method == 'POST':
        contact_number = request.POST.get('contact_number')
        image = request.FILES['upload']
        user = request.user
        profile = Profile(user=user,image=image,contact_number=contact_number)
        profile.save()
    return render(request,'users/createprofile.html')

def seller_profile(request,id):
    seller = User.objects.get(id=id)
    context = {
        'seller':seller
    }
    return render(request,'users/sellerprofile.html', context)

myapp/templates/myapp/addproduct.html
{% extends 'myapp/base.html'%}
{% block content %}
<h1 class="text-2xl font-bold m-10">➕Add Product</h1>
<form class="bg-white shadow-md m-10 px-8 py-8 w-3/5" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="mb-4">
        <label class="block text-gray-700 text-sm font-bold mb-2 " for="">Product Name</label>
        <input class="shadow apperance-none border rounded py-2 px-3 mr-10 text-gray-500" placeholder="name" type="text" name="name" id="name">
    </div>
    <div class="mb-4">
        <label class="block text-gray-700 text-sm font-bold mb-2 " for="">Product Price</label>
        <input class="shadow apperance-none border rounded py-2 px-3 mr-10 text-gray-500" placeholder="price" type="text" name="price" id="price">
    </div>
    <div class="mb-4">
        <label class="block text-gray-700 text-sm font-bold mb-2 " for="">Product Description</label>
        <input class="shadow apperance-none border rounded py-2 px-3 mr-10 text-gray-500" placeholder="desc" type="text" name="desc" id="desc">
    </div>
    <div class="mb-4">
        <label class="block text-gray-700 text-sm font-bold mb-2 " for="">Product Image</label>
        <input class="py-2" type="file" accept="image/*" name="upload" id="upload">
    </div>
    <div class="mb-4">
        <input class="text-green-500 text-white px-5 py-2" type="submit" name="add product" value="add product">
    </div>
</form>
{% endblock %}

myapp/templates/myapp/base.html
{% load static%}
<html>
    <head>
        <link rel="stylesheet" href="{% static 'myapp/styles.css'%}">
    </head>
    <body>
        <nav class="bg-white shadow-lg">
            <div class="max-w-6xl mx-auto px-4">
                <div class="flex justify-between">
                    <div class="flex space-x-7">
                        <div>
                            <a href="#" class="flex px-2 py-4 items-center">
                            <img class="h-8 w-8" src="{% static 'myapp/images/mechanic.png' %}" alt="">
                            <span class="text-gray-500 font-semibold text-lg">Buy&Sell</span>
                            </a>
                        </div>
                        <div class="items-center flex space-x-1">
                            <a href="#" class="px-2 py-4 text-gray-500 font-semibold border-b-4 border-green-500">Home</a>
                            <a href="{% url 'myapp:add_product'%}" class="px-2 py-4 text-gray-500 font-semibold">Post Ad</a>
                            <a href="{% url 'myapp:product'%}" class="px-2 py-4 text-gray-500 font-semibold">View Product</a>
                            {% if user.is_authenticated %}
                                <a class="px-20 py-4 text-gray-500 font-semibold" href="{% url 'users:logout' %}">Logout</a>
                                <a class="px-40 py-4 text-gray-500 font-semibold" href="{% url 'users:profile' %}">Profile</a>
                                <a class="py-4 text-gray-500 font-semibold" href="{% url 'myapp:mylistings' %}">MyListings</a>
                            {% else %}
                                <a class="px-40 py-4 text-gray-500 font-semibold" href="{% url 'users:login' %}">Login</a>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </nav>
        {% block content %}
        
        {% endblock %}
    </body>
</html>

myapp/templates/myapp/delete.html
{% extends 'myapp/base.html'%}
{% block content %}
<h1 class="text-2xl font-bold m-10">Delete Product</h1>
<form method="post" class="bg-white m-10 shadow-10 w-3/5 rounded px-8 pt-6 pb-8 mb-4">
    {% csrf_token %}
    <div class="mb-4">
        <label class="block text-gray-700 text-sm font-bold mb-2">Are you sure you want to delete this product</label>
    </div>
    <div class="mb-4">
        <label class="block text-gray-700 text-sm font-bold mb-2">{{product.name}}</label>
    </div>
    <div class="mb-4">
        <img src="{{product.image.url}}">
    </div>
    <input class="bg-red-500 text-white px-5 py-2" type="submit" name="Confirm" value="Confirm">
    <a class="button bg-green-500 text-white px-5 py-3" href="{% url 'myapp:product'%}">Cancel</a>
</form>
{% endblock %}

myapp/templates/myapp/detail.html
{% extends 'myapp/base.html'%}
{% block content %}
<div class="flex p-10 w-full h-200">
    <img class="w-1/3" src="{{product.image.url}}" alt="">
    <div class="w-2/3 text-xl ml-10 mt-10">
        <div class="mt-5">{{product.name}}</div>
        <div class="mt-5 text-green-500">{{product.price}}</div>
        <div class="mt-5 text-gray-700">{{product.desc}}</div>
        <div class="mt-5 text-gray-700">Seller name: <a href="{% url 'users:sellerprofile' product.seller_name.id%}">{{product.seller_name}}</a></div>
        <div class="mt-5 text-gray-700">Contact: {{product.seller_name.profile.contact_number}}</div>
    </div>
    
</div>
{% endblock %}

myapp/templates/myapp/index.html
{% extends 'myapp/base.html'%}
{% load static %}
{% block content %}
    
    <!--Site hero starts here-->
    <main class="mt-10 mx-auto max-w-7xl px-4 sm:st-12 sm:px-6 md:mt-16 lg:mt-20 lg:-px-8 xl:mt-28 ">
        <div class="sm:text-center lg:text-left">
            <h1 class="text-4xl font-extrabold text-gray-900 sm:text-5xl md:text-6xl">
                <span class="block xl:inline">premium products</span>
                <span class="block text-green-500 xl:inline">Non-Premiium prices</span>
            </h1>
            <p class="mt-3 text-base text-gray-500 sm:mt-5 sm:text-lg sm:max-w-xl sm:max-auto md:mt-5 md:text-xl lg:mx-0">Get the best quality product used across globe and free shipping</p>
        </div>
    </main>
    <!--Site hero ends here-->
    <div class="flex mt-5 p-10 justify-center">
        <h2 class="text-3xl font-normal mt-0 mb-2 text-gray-500">Recent Products</h2>
    </div>

    <div class="mt-10 p-5 justify-center">
        <h2>Search Products</h2>
        <form method="get">
            <input class="font-bold text-lg text-gray-700 " name="product_name" id="product_name" placeholder="Type a product to search" type="text">
        </form>
    </div>

    <div class="p-10 grid grid-cols-1 sm:grid-cols-1 md:grid-cols-3 xl:grid-cols-3 lg:grid-cols-3 gap-5">
        <!--Card1-->
        {% for product in page_obj %}
        <a href="{% url 'myapp:product_detail' product.id%}">
            <div class="rounded overflow-hidden shadow-lg">
                <img class="w-full" src="{{product.image.url}}" >
                <div class="px-6 py-4">
                    <div class="font-bold text-xl mb-2">{{product.name}}</div>
                    <div class="font-bold text-xl text-green-500 mb-2">${{product.price}}</div>
                    <div class="mb-2 font-bold">Posted by: <span class="text-indigo-500">{{product.seller_name}}</span></div>
                    <p class="text-gray-700 text-base">{{product.desc}}</p>
                </div>
            </div>
        </a>
        {% endfor %}
    </div>
    <!--Pagination starts here-->
    <div class="pagination flex justify-center items-center mb-20">
        <span>
            {% if page_obj.has_previous %}
            <a class="text-sm font-medium border py-2 px-4 items-center inline-flex relative text-green-500 border-green-500 z-10" href="?page=1">First</a>
            <a class="text-sm font-medium border py-2 px-4 items-center inline-flex relative text-green-500 border-green-500 z-10" href="?page={{page_obj.previous_page_number}}">Previous</a>
            {% endif %}
            <span class="text-sm font-medium border py-2 px-4 items-center inline-flex relative text-green-500 border-green-500 z-10">
                Page {{page_obj.number}} of {{page_obj.paginator.num_pages}}
            </span>

            {% if page_obj.has_next %}
            <a class="text-sm font-medium border py-2 px-4 items-center inline-flex relative text-green-500 border-green-500 z-10" href="?page={{page_obj.next_page_number}}">Next</a>
            <a class="text-sm font-medium border py-2 px-4 items-center inline-flex relative text-green-500 border-green-500 z-10" href="?page={{page_obj.paginator.num_pages}}">Last</a>
            {% endif %}
        </span>
    </div>
    <!--Pagination ends here-->
{% endblock %}

myapp/templates/myapp/mylisting.html
{% extends 'myapp/base.html' %}
{% block content %}
<div class="text-2xl m-10 p-10 font-bold">📘 MyListings</div>
{% for prod in product %}
<div class="itemcontainer flex shadow-lg m-10 p-10">
    <span class="w-1/5"><img class="w-40 h-40" src="{{prod.image.url}}" alt=""></span>
    <span class="w-2/5">
        <div class="font-bold text-gray-700">{{prod.name}}</div>
        <div class="text-green-500">{{prod.price}}</div>
        <div>{{prod.desc}}</div>
    </span>
    <span class="w-1/5 my-10 mx-10">
        <a class="bg-green-500 text-white font-bold px-5 py-2" href="{% url 'myapp:update_product' prod.id %}">Edit</a>
    </span>
    <span class="w-1/5 my-10 mx-10">
        <a class="bg-red-500 text-white font-bold px-5 py-2" href="{% url 'myapp:delete_product' prod.id%}">Delete</a>
    </span>
</div>
{% endfor %}
{%endblock%} 

myapp/templates/myapp/myproduct_form.html
{% extends 'myapp/base.html'%}
{% block content %}
<h1 class="text-2xl font-bold m-10">➕Add Product</h1>
<form class="bg-white shadow-md m-10 px-8 py-8 w-3/5" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="mb-4">
        <label class="block text-gray-700 text-sm font-bold mb-2 " for="">Product Name</label>
        <div class="w-1/4 shadow apperance-none border rounded py-2 px-3 mr-10 text-gray-500">
            {{form.name}}
        </div>
    </div>
    <div class="mb-4">
        <label class="block text-gray-700 text-sm font-bold mb-2 " for="">Product Price</label>
        <div class="w-1/4 shadow apperance-none border rounded py-2 px-3 mr-10 text-gray-500">
            {{form.price}}
        </div>
    </div>
    <div class="mb-4">
        <label class="block text-gray-700 text-sm font-bold mb-2 " for="">Product Description</label>
        <div class="w-1/4 shadow apperance-none border rounded py-2 px-3 mr-10 text-gray-500">
            {{form.desc}}
        </div>
    </div>
    <div class="mb-4">
        <label class="block text-gray-700 text-sm font-bold mb-2 " for="">Product Image</label>
        <div class="w-1/4 shadow apperance-none border rounded py-2 px-3 mr-10 text-gray-500">
            {{form.image}}
        </div>
    </div>
    <div class="mb-4">
        <div class="hidden w-1/4 shadow apperance-none border rounded py-2 px-3 mr-10 text-gray-500">
            {{form.seller_name}}
        </div>
    </div>
    <div class="mb-4">
        <input class="text-green-500 text-white px-5 py-2" type="submit" name="add product" value="add product">
    </div>
</form>
{% endblock %}

myapp/templates/myapp/updateproduct.html
{% extends 'myapp/base.html'%}
{% block content %}
<h1 class="text-2xl font-bold m-10">➕Update Product</h1>
<form class="bg-white shadow-md m-10 px-8 py-8 w-3/5" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="mb-4">
        <label class="block text-gray-700 text-sm font-bold mb-2 " for="">Product Name</label>
        <input class="shadow apperance-none border rounded py-2 px-3 mr-10 text-gray-500" placeholder="name" value="{{product.name}}" type="text" name="name" id="name">
    </div>
    <div class="mb-4">
        <label class="block text-gray-700 text-sm font-bold mb-2 " for="">Product Price</label>
        <input class="shadow apperance-none border rounded py-2 px-3 mr-10 text-gray-500" placeholder="price" value="{{product.price}}" type="text" name="price" id="price">
    </div>
    <div class="mb-4">
        <label class="block text-gray-700 text-sm font-bold mb-2 " for="">Product Description</label>
        <input class="shadow apperance-none border rounded py-2 px-3 mr-10 text-gray-500" placeholder="desc" value="{{product.desc}}" type="text" name="desc" id="desc">
    </div>
    <div class="mb-4">
        <img class="w-20 h-20" src="{{product.image.url}}" alt="">
        <label class="block text-gray-700 text-sm font-bold mb-2 " for="">Product Image</label>
        <input class="py-2" type="file" accept="image/*" name="upload" id="upload">
    </div>
    <div class="mb-4">
        <input class="text-green-500 text-white px-5 py-2" type="submit" name="add product" value="Update product">
    </div>
</form>
{% endblock %}

users/templates/users/createprofile.html
{% extends 'myapp/base.html' %}
{% block content %}
<form method="post" enctype="multipart/form-data" class="bg-white shadow-md m-10 w-3/5 rounded px-8 pt-6 pb-8 mb-4">
    {% csrf_token %}
    <div class="mb-4">
        <label for="">Upload profile image</label>
        <input class="py-2" type="file" accept="image/*" name="upload" id="upload" placeholder="Upload a clear profile image">
    </div>
    <div class="mb-4">
        <label for="">Upload Contact</label>
        <input class="shadow appearance-none border rounded py-2 px-3 mr-10 text-gray-700" type="text"  name="contact_number" id="contact_number" placeholder="9999999999">
    </div>
    <input class="bg-green-500 text-white  px-5 py-2" name="add" value="add" type="submit">
</form>
{% endblock %}

users/templates/users/login.html
{% extends 'myapp/base.html'%}
{% block content %}

<h1 class="text-2xl m-10 font-bold">Login user</h1>
<div class="container py-5">
    <form class="w-2/5 bg-white shadow-md m-10 rounded px-8 pt-6 pb-8 mb-4" method="post" >
        {% csrf_token %}
        <div class="mb-2">
            <label class="text-gray-700 block text-sm font-bold mb-2">Username</label>
            <div class="shadow appearance-none border rounded py-2 px-3 mr-10 text-gray-700 leading-tight">
                {{form.username}}
            </div>
        </div>
        <div class="mb-2">
            <label class="text-gray-700 block text-sm font-bold mb-2">Password</label>
            <div class="shadow appearance-none border rounded py-2 px-3 mr-10 text-gray-700 leading-tight">
                {{form.password}}
            </div>
        </div>
        <button class="bg-green-500 text-white px-5 py-2" type="submit">Login</button>
    </form>
    <div class="m-10">Do not have an Account? <a class="text-indigo-500" href="{% url 'users:register'%}">Register</a></div>
</div>

{% endblock %}

users/templates/users/logout.html
{% extends 'myapp/base.html'%}
{% block content %}
<h1>You have been loged out of a page</h1>
{% endblock %}

users/templates/users/profile.html
{% extends 'myapp/base.html'%}
{% block content %}
<div class="grid p-10 grid-cols-1 lg:grid-cols-3 sm:grid-cols-1">
    <div class="rounded shadow-lg">
        <div>
            <img src="{{user.profile.image.url}}" alt="">
        </div>
        <div class="font-bold text-xl mb-2 py-4 px-6">
            {{user.username}}
        </div>
        <div class="font-bold text-xl mb-2 py-4 px-6">
            📞 {{user.profile.contact_number}}
        </div>
    </div>
</div>
{% endblock %}

users/templates/users/register.html
{% extends 'myapp/base.html'%}
{% block content %}

<h1 class="text-2xl m-10 font-bold">Register user</h1>
<div class="container py-5">
    <form class="w-2/5 bg-white shadow-md m-10 rounded px-8 pt-6 pb-8 mb-4" method="post" >
        {% csrf_token %}
        <div class="mb-2">
            <label class="text-gray-700 block text-sm font-bold mb-2">Username</label>
            <div class="shadow appearance-none border rounded py-2 px-3 mr-10 text-gray-700 leading-tight">
                {{form.username}}
            </div>
        </div>
        <div class="mb-2">
            <label class="text-gray-700 block text-sm font-bold mb-2">Email</label>
            <div class="shadow appearance-none border rounded py-2 px-3 mr-10 text-gray-700 leading-tight">
                {{form.email}}
            </div>
        </div>
        <div class="mb-2">
            <label class="text-gray-700 block text-sm font-bold mb-2">Password</label>
            <div class="shadow appearance-none border rounded py-2 px-3 mr-10 text-gray-700 leading-tight">
                {{form.password1}}
            </div>
        </div>
        <div class="mb-2">
            <label class="text-gray-700 block text-sm font-bold mb-2">Confirm password</label>
            <div class="shadow appearance-none border rounded py-2 px-3 mr-10 text-gray-700 leading-tight">
                {{form.password2}}
            </div>
        </div>
        <button class="bg-green-500 text-white px-5 py-2" type="submit">Register</button>
    </form>
    <div class="m-10">Already have an Account? <a class="text-indigo-500" href="{% url 'users:login'%}">Insted Login</a></div>
</div>

{% endblock %}

users/templates/users/sellerprofile.html
{% extends 'myapp/base.html'%}
{% block content %}
<div class="grid p-10 grid-cols-1 lg:grid-cols-3 sm:grid-cols-1">
    <div class="rounded shadow-lg">
        <div>
            <img src="{{seller.profile.image.url}}" alt="">
        </div>
        <div class="font-bold text-xl mb-2 py-4 px-6">
            {{seller.username}}
        </div>
        <div class="font-bold text-xl mb-2 py-4 px-6">
            📞 {{seller.profile.contact_number}}
        </div>
    </div>
</div>
{% endblock %}